run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - goimports
  disable:
    - wsl

linters-settings:
  gosec:
    excludes:
      - "G104"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck