name: Segmentation CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest      # <- либо убираем sudo вместо этого
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.3"

      - name: Download dependencies
        run: go mod tidy && go mod download

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler build-essential
          protoc --version

      - name: Install Go protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - name: Generate protobuf code
        env:
          PATH: ${{ env.PATH }}:${{ env.GOPATH }}/bin
        run: make gen

      - name: Spin up infra
        run: |
          make run-infra
          sleep 20

      - name: Spin up app
        run: |
          make run-local
          sleep 10

      - name: Run tests
        run: make tests
